### ISSUE TITLE
ImportError: No module named resources

### ISSUE THREAD

**Issue by r3comp1le** [buffer/thug#118]
python thug.py -h

Traceback (most recent call last):
  File "thug.py", line 24, in <module>
    from ThugAPI import *
  File "/opt/thug/src/ThugAPI/__init__.py", line 1, in <module>
    from .ThugAPI import ThugAPI
  File "/opt/thug/src/ThugAPI/ThugAPI.py", line 34, in <module>
    from DOM import MIMEHandler
  File "/opt/thug/src/DOM/MIMEHandler.py", line 51, in <module>
    from Analysis.androguard.core.bytecodes import apk
  File "/opt/thug/src/Analysis/androguard/core/bytecodes/apk.py", line 24, in <module>
    from androguard.core.resources import public as SYSTEM_RESOURCES
ImportError: No module named resources

**Comment by r3comp1le** [comment]
androguard is missing the entire Resources folder

**Comment by buffer** [comment]
I can't reproduce the issue. Could you please tell me which version of Thug you are using?

**Comment by yuunaka1** [comment]
I can reproduce the issue when I use current master branch.

**Comment by buffer** [comment]
My fault. Submitting a patch right now.
