### ISSUE TITLE
RuntimeError: Lock should be acquired before enter the context

### ISSUE THREAD

**Issue by pdelsante** [buffer/thug#136]
As agreed on the phone, there seems to be an issue while handling iframes:
```
Traceback (most recent call last):
  File "thug.py", line 268, in <module>
    main()
  File "thug.py", line 259, in main
    Thug(sys.argv[1:])()
  File "/home/pdelsante/bin/thug/src/ThugAPI/ThugAPI.py", line 73, in __call__
    self.analyze()
  File "thug.py", line 250, in analyze
    p(args[0])
  File "/home/pdelsante/bin/thug/src/ThugAPI/ThugAPI.py", line 283, in run_remote
    self.run(window)
  File "/home/pdelsante/bin/thug/src/ThugAPI/ThugAPI.py", line 255, in run
    dft.run()
  File "/home/pdelsante/bin/thug/src/DOM/DFT.py", line 1234, in run
    self._run()
  File "/home/pdelsante/bin/thug/src/DOM/DFT.py", line 1186, in _run
    if not self.do_handle(child):
  File "/home/pdelsante/bin/thug/src/DOM/DFT.py", line 1164, in do_handle
    handler(child)
  File "/home/pdelsante/bin/thug/src/DOM/DFT.py", line 1006, in handle_iframe
    self.handle_frame(iframe, 'iframe')
  File "/home/pdelsante/bin/thug/src/DOM/DFT.py", line 1003, in handle_frame
    dft.run()
  File "/home/pdelsante/bin/thug/src/DOM/DFT.py", line 1232, in run
    with PyV8.JSLocker():
  File "build/bdist.linux-x86_64/egg/PyV8.py", line 166, in __enter__
RuntimeError: Lock should be acquired before enter the context
```

To reproduce this issue, you can try the following page (tested at the moment of writing):
```
http://www.advisoronline.it/home.action
```

**Comment by buffer** [comment]
It seems like the JSLocker lock is acquired too late thus disrupting the recursive frame/iframe handling. I am going to submit a patch which should solve the issue in a few minutes. I tested it here and it works fine. Please let me know if it fixes the bug for you as well. Thanks.

**Comment by pdelsante** [comment]
Thanks a lot, I tried that page several times and it seems to be fixed now! I'm closing the issue.
