### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by DigiAngel** [buffer/thug#180]
Here's the run:
~~~
[2016-09-09 16:30:30] [WARNING] Androguard not found - APK analysis disabled
[2016-09-09 16:30:30] ActiveXObject: wscript.shell
[2016-09-09 16:30:30] [window open redirection] about:blank -> meow://Aadreezzcinemedia[.]net/JHgy64HJBRd
[2016-09-09 16:30:33] [HTTP] URL: meow://Aadreezzcinemedia[.]net/JHgy64HJBRd (Status: 200, Referer: None)
[2016-09-09 16:30:33] [HTTP] URL: meow://Aadreezzcinemedia[.]net/JHgy64HJBRd (Content-type: text/plain, MD5: e1e87ef61248716a5a6deca42c6dd7c5)
[2016-09-09 16:30:36] ActiveXObject: wscript.shell
Traceback (most recent call last):
  File "/opt/thug/src/thug.py", line 268, in <module>
    main()
  File "/opt/thug/src/thug.py", line 259, in main
    Thug(sys.argv[1:])()
  File "/opt/thug/src/ThugAPI/ThugAPI.py", line 78, in __call__
    self.analyze()
  File "/opt/thug/src/thug.py", line 250, in analyze
    p(args[0])
  File "/opt/thug/src/ThugAPI/ThugAPI.py", line 296, in run_remote
    self.run(window)
  File "/opt/thug/src/ThugAPI/ThugAPI.py", line 261, in run
    dft.run()
  File "/opt/thug/src/DOM/DFT.py", line 1251, in run
    self._run()
  File "/opt/thug/src/DOM/DFT.py", line 1202, in _run
    if not self.do_handle(child):
  File "/opt/thug/src/DOM/DFT.py", line 1178, in do_handle
    handler = getattr(self, "handle_%s" % (str(name.lower()), ), None)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xba' in position 2: ordinal not in range(128)
~~~

This is a #locky data file download.  Thank you.

**Comment by buffer** [comment]
Can you please re-run Thug with the -F and -v options and send me (even privately) all the logs it generates? I would like to take a look at what is going on. Thanks!

**Comment by DigiAngel** [comment]
Ok....pretty sure this is because the response back has nothing to do with http :D.  This is a #locky encrypted data file:
~~~
root@e069b97aad33:/opt# python /opt/thug/src/thug.py -F -v -p socks4://192.168.1.253:9050 meow://dpskaunas.puslapiai.lt/g76gyui
[2016-09-10 15:40:10] [WARNING] Androguard not found - APK analysis disabled
[2016-09-10 15:40:10] ActiveXObject: wscript.shell
[2016-09-10 15:40:10] [window open redirection] about:blank -> meow://dpskaunas.puslapiai.lt/g76gyui
[2016-09-10 15:40:13] [HTTP] URL: meow://dpskaunas.puslapiai.lt/g76gyui (Status: 404, Referer: None)
[2016-09-10 15:40:13] [HTTP] URL: meow://dpskaunas.puslapiai.lt/g76gyui (Content-type: text/html; charset=iso-8859-1, MD5: 0b116602607dd77f870ccfa7e39ea70b)
[2016-09-10 15:40:13] Thug analysis logs saved at ../logs/16aeca5ceac17a96314795869da05d2e/20160910154010
root@e069b97aad33:/opt# python /opt/thug/src/thug.py -F -v -p socks4://192.168.1.253:9050 meow://158.195.68[.]10/g76gyui       
[2016-09-10 15:40:39] [WARNING] Androguard not found - APK analysis disabled
[2016-09-10 15:40:39] ActiveXObject: wscript.shell
[2016-09-10 15:40:39] [window open redirection] about:blank -> meow://158.195.68[.]10/g76gyui
[2016-09-10 15:40:42] [HTTP] URL: meow://158.195.68[.]10/g76gyui (Status: 200, Referer: None)
[2016-09-10 15:40:42] [HTTP] URL: meow://158.195.68[.]10/g76gyui (Content-type: unknown, MD5: 68fdf7efd67dd23d5322db55f4353be7)
[2016-09-10 15:40:44] ActiveXObject: wscript.shell
Traceback (most recent call last):
  File "/opt/thug/src/thug.py", line 268, in <module>
    main()
  File "/opt/thug/src/thug.py", line 259, in main
    Thug(sys.argv[1:])()
  File "/opt/thug/src/ThugAPI/ThugAPI.py", line 78, in __call__
    self.analyze()
  File "/opt/thug/src/thug.py", line 250, in analyze
    p(args[0])
  File "/opt/thug/src/ThugAPI/ThugAPI.py", line 296, in run_remote
    self.run(window)
  File "/opt/thug/src/ThugAPI/ThugAPI.py", line 261, in run
    dft.run()
  File "/opt/thug/src/DOM/DFT.py", line 1251, in run
    self._run()
  File "/opt/thug/src/DOM/DFT.py", line 1202, in _run
    if not self.do_handle(child):
  File "/opt/thug/src/DOM/DFT.py", line 1178, in do_handle
    handler = getattr(self, "handle_%s" % (str(name.lower()), ), None)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb7' in position 2: ordinal not in range(128)
~~~

and contents:
~~~
[09:41:27 gateway:~/careful$] hexdump g76gyui | head
00000000  7b 1e ff 58 57 6c 6d 36  55 68 76 49 89 99 7a 30  |{..XWlm6UhvI..z0|
00000010  8b 35 70 44 68 48 52 70  15 63 4c 50 41 4f 6d 48  |.5pDhHRp.cLPAOmH|
00000020  36 44 6f 58 54 6c 6d 36  51 68 76 49 76 66 7a 30  |6DoXTlm6QhvIvfz0|
00000030  33 35 70 44 68 48 52 70  55 63 4c 50 91 4f 6d 48  |35pDhHRpUcLP.OmH|
00000040  38 5b d5 56 54 d8 64 fb  70 d0 77 05 bb 47 2e 58  |8[.VT.d.p.w..G.X|
00000050  5a 46 50 34 1a 27 35 02  34 0e 6c 33 20 21 03 27  |ZFP4.'5.4.l3 !.'|
00000060  42 64 0d 3d 74 1e 18 58  71 01 18 69 32 29 29 10  |Bd.=t..Xq..i2)).|
00000070  5e 5a 14 21 46 45 5f 7a  71 63 4c 50 41 4f 6d 48  |^Z.!FE_zqcLPAOmH|
00000080  9d 88 48 32 bb c1 24 0f  be c5 3f 70 99 cb 33 09  |..H2..$...?p..3.|
00000090  34 87 33 7d 83 e5 1b 49  52 d1 01 69 ac e2 24 71  |4.3}...IR..i..$q|
~~~

Thank you!

**Comment by buffer** [comment]
Could you please check the effectiveness of the fix? Thanks!

**Comment by DigiAngel** [comment]
Thanks for the quick work...truth be told I'm using thug in a docker environment:  [https://hub.docker.com/r/remnux/thug/](url) and I'm not entirely sure how/when that gets updated.  I'll see what I can do to get it updated...thanks again.

**Comment by buffer** [comment]
FYI you can test the last changes with a docker I provide which is automatically rebuilt after each single commit. Please take a look at http://buffer.github.io/thug/doc/docker.html for additional details.

**Comment by DigiAngel** [comment]
Ok sweet...here's the hash on the docker image:  sha256:91d0875e93153df9405fecca42a33158935db198fbe71c2750172ae538f56362

so here's what I get:
~~~
root@ec9bafa071c6:/opt# python /opt/thug/src/thug.py -p socks4://192.168.1.253:9050 'meow://syamasahithi[.]com/8fh34f3?vSStXSLa=GvaNcpO'                                                                                               
[2016-09-12 11:50:44] [WARNING] Androguard not found - APK analysis disabled
[2016-09-12 11:50:44] ActiveXObject: wscript.shell
[2016-09-12 11:50:44] [window open redirection] about:blank -> meow://syamasahithi[.]com/8fh34f3?vSStXSLa=GvaNcpO
root@ec9bafa071c6:/opt# 
~~~

I no longer get an error, but I don't get the file either :(  Manual getting I do:
~~~
--2016-09-12 05:51:06--  meow://syamasahithi[.]com/8fh34f3?vSStXSLa=GvaNcpO
Resolving syamasahithi[.]com (syamasahithi[.]com)... 131.153.37.4
Connecting to syamasahithi[.]com (syamasahithi[.]com)|131.153.37.4|:80... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  Date: Mon, 12 Sep 2016 11:51:08 GMT
  Server: Apache
  Last-Modified: Mon, 12 Sep 2016 10:51:28 GMT
  Accept-Ranges: bytes
  Content-Length: 240944
  Keep-Alive: timeout=5, max=100
  Connection: Keep-Alive
Length: 240944 (235K)
Saving to: ‘8fh34f3?vSStXSLa=GvaNcpO’

100%[=================>] 240,944      258KB/s   in 0.9s   

2016-09-12 05:51:09 (258 KB/s) - ‘8fh34f3?vSStXSLa=GvaNcpO’ saved [240944/240944]

[05:51:09  gateway:~/careful$] file 8fh34f3\?vSStXSLa\=GvaNcpO 
8fh34f3?vSStXSLa=GvaNcpO: data
~~~

Thank you!

**Comment by buffer** [comment]
It seems like something is going wrong there because I was able to get the file experiencing no issues at all.

**Comment by DigiAngel** [comment]
Weird....going to google it works as well as tells me I'm from somewhere I'm not:
![2016-09-12 09_32_18-zone](https://cloud.githubusercontent.com/assets/947191/18441893/e7932b5a-78cb-11e6-8192-5a6d8440f892.jpg)

Eh...I'll just chalk it up to weirdness and drive on.  Thanks again.
