### ISSUE TITLE
ImportError: /usr/local/lib/python2.7/dist-packages/pygraphviz/_graphviz.so: undefined symbol: Agundirected

### ISSUE THREAD

**Issue by standa4** [buffer/thug#189]
Hello,
thank you for resolving the issue with building docker image but now I have problem to run thug in container created from this image. The same is with version from dockerhub (buffer/thug).
When I call docker run I get following error:

Traceback (most recent call last):
  File "/usr/local/bin/thug", line 11, in <module>
    load_entry_point('thug==0.8.8', 'console_scripts', 'thug')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2631, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2291, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2297, in resolve
  File "/usr/local/lib/python2.7/dist-packages/thug/thug.py", line 24, in <module>
    from .ThugAPI import ThugAPI
  File "/usr/local/lib/python2.7/dist-packages/thug/ThugAPI/__init__.py", line 1, in <module>
    from .ThugAPI import ThugAPI
  File "/usr/local/lib/python2.7/dist-packages/thug/ThugAPI/ThugAPI.py", line 42, in <module>
    from thug.Logging.ThugLogging import ThugLogging
  File "/usr/local/lib/python2.7/dist-packages/thug/Logging/ThugLogging.py", line 21, in <module>
    from .LoggingModules import LoggingModules
  File "/usr/local/lib/python2.7/dist-packages/thug/Logging/LoggingModules.py", line 20, in <module>
    from .modules import JSON
  File "/usr/local/lib/python2.7/dist-packages/thug/Logging/modules/JSON.py", line 32, in <module>
    from .Mapper import Mapper
  File "/usr/local/lib/python2.7/dist-packages/thug/Logging/modules/Mapper.py", line 29, in <module>
    import pygraphviz
  File "/usr/local/lib/python2.7/dist-packages/pygraphviz/__init__.py", line 58, in <module>
    from .agraph import AGraph, Node, Edge, Attribute, ItemAttribute, DotError
  File "/usr/local/lib/python2.7/dist-packages/pygraphviz/agraph.py", line 26, in <module>
    from . import graphviz as gv
  File "/usr/local/lib/python2.7/dist-packages/pygraphviz/graphviz.py", line 28, in <module>
    _graphviz = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/pygraphviz/graphviz.py", line 24, in swig_import_helper
    _mod = imp.load_module('_graphviz', fp, pathname, description)
ImportError: /usr/local/lib/python2.7/dist-packages/pygraphviz/_graphviz.so: undefined symbol: Agundirected

Thank you for your help.

**Comment by standa4** [comment]
After some googling I found that the workaround is to reinstall pygraphviz after the thug is installed and specify where to look for libraries. The command is:
`RUN pip install pygraphviz --install-option="--include-path=/usr/include/graphviz" --install-option="--library-path=/usr/lib/graphviz/" --upgrade --force-reinstall` 
I added this command after installation of thug (pip install thug).

**Comment by buffer** [comment]
@pdelsante do you think it is worth adding to the Dockerfile?
