### ISSUE TITLE
No configuration directory after installation

### ISSUE THREAD

**Issue by cybext** [buffer/thug#197]
After I've completely installed thug, I have no configuration files and no thug directory at all under /etc
So every time I run thug it doesn't work correctly.

**Comment by buffer** [comment]
Did it happen after a fresh install or after an update? Can you please provide additional details?

**Comment by cybext** [comment]
it was a fresh installation in Ubuntu. I installed using:
`sudo -H pip install thug`

and when I run it:
`$ thug "http://www.site.com"
[2017-01-18 11:42:44] [HTML Classifier] Skipping not existing default classification rule file
[2017-01-18 11:42:44] [HTML Classifier] Skipping not existing default filter file
[2017-01-18 11:42:44] [JS Classifier] Skipping not existing default classification rule file
[2017-01-18 11:42:44] [JS Classifier] Skipping not existing default filter file
[2017-01-18 11:42:44] [VBS Classifier] Skipping not existing default classification rule file
[2017-01-18 11:42:44] [VBS Classifier] Skipping not existing default filter file
[2017-01-18 11:42:44] [URL Classifier] Skipping not existing default classification rule file
[2017-01-18 11:42:44] [URL Classifier] Skipping not existing default filter file
[2017-01-18 11:42:44] [Sample Classifier] Skipping not existing default classification rule file
[2017-01-18 11:42:44] [Sample Classifier] Skipping not existing default filter file
[2017-01-18 11:42:44] [WARNING] VirusTotal disabled (no configuration file found)
[2017-01-18 11:42:44] [CRITICAL] Logging subsystem not initialized (configuration file not found)
Traceback (most recent call last):
  File "/usr/local/bin/thug", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/thug/thug.py", line 324, in main
    Thug(sys.argv[1:])()
  File "/usr/local/lib/python2.7/dist-packages/thug/ThugAPI/ThugAPI.py", line 80, in __call__
    self.analyze()
  File "/usr/local/lib/python2.7/dist-packages/thug/thug.py", line 314, in analyze
    ThugPlugins(PRE_ANALYSIS_PLUGINS, self)()
  File "/usr/local/lib/python2.7/dist-packages/thug/Plugins/ThugPlugins.py", line 44, in __init__
    self.get_plugins()
  File "/usr/local/lib/python2.7/dist-packages/thug/Plugins/ThugPlugins.py", line 68, in get_plugins
    for p in os.listdir(PLUGINS_PATH):
OSError: [Errno 2] No such file or directory: '/etc/thug/plugins'
`

**Comment by buffer** [comment]
Can you please try reinstalling by first executing "sudo pip uninstall thug" (do it multiple times for avoiding dead installations file around) and then "sudo pip install thug"?

**Comment by cybext** [comment]
Thanks a lot. It did actually work. It was the -H flag of sudo messing with it.

**Comment by buffer** [comment]
Nice to know! Thanks!
