### ISSUE TITLE
First time set-up problems.

### ISSUE THREAD

**Issue by Waffles-2** [buffer/thug#206]
Hi, firstly I am on Ubuntu 16.04 and have gone through the Thug installation guide multiple time and am currently stuck as where to go from here. I installed all packages except HoneyAgent & VirusTotal (both optional). My problem is that when I run `thug --list-ua` I get this: 
```

[2017-03-28 10:11:03] [HTML Classifier] Skipping not existing default classification rule file
[2017-03-28 10:11:03] [HTML Classifier] Skipping not existing default filter file
[2017-03-28 10:11:03] [JS Classifier] Skipping not existing default classification rule file
[2017-03-28 10:11:03] [JS Classifier] Skipping not existing default filter file
[2017-03-28 10:11:03] [VBS Classifier] Skipping not existing default classification rule file
[2017-03-28 10:11:03] [VBS Classifier] Skipping not existing default filter file
[2017-03-28 10:11:03] [URL Classifier] Skipping not existing default classification rule file
[2017-03-28 10:11:03] [URL Classifier] Skipping not existing default filter file
[2017-03-28 10:11:03] [Sample Classifier] Skipping not existing default classification rule file
[2017-03-28 10:11:03] [Sample Classifier] Skipping not existing default filter file
[2017-03-28 10:11:03] [Text Classifier] Skipping not existing default classification rule file
[2017-03-28 10:11:03] [Text Classifier] Skipping not existing default filter file

Synopsis:
    Thug: Pure Python honeyclient implementation

    Available User-Agents:
```

So lots of skipping, I don't know if that is a problem but no User-Agents?
Also when I try to run Thug I get the following: 

```
[2017-03-28 10:15:41] [HTML Classifier] Skipping not existing default classification rule file
[2017-03-28 10:15:41] [HTML Classifier] Skipping not existing default filter file
[2017-03-28 10:15:41] [JS Classifier] Skipping not existing default classification rule file
[2017-03-28 10:15:41] [JS Classifier] Skipping not existing default filter file
[2017-03-28 10:15:41] [VBS Classifier] Skipping not existing default classification rule file
[2017-03-28 10:15:41] [VBS Classifier] Skipping not existing default filter file
[2017-03-28 10:15:41] [URL Classifier] Skipping not existing default classification rule file
[2017-03-28 10:15:41] [URL Classifier] Skipping not existing default filter file
[2017-03-28 10:15:41] [Sample Classifier] Skipping not existing default classification rule file
[2017-03-28 10:15:41] [Sample Classifier] Skipping not existing default filter file
[2017-03-28 10:15:41] [Text Classifier] Skipping not existing default classification rule file
[2017-03-28 10:15:41] [Text Classifier] Skipping not existing default filter file
[2017-03-28 10:15:41] [WARNING] VirusTotal disabled (no configuration file found)
[2017-03-28 10:15:41] [CRITICAL] Logging subsystem not initialized (configuration file not found)
Traceback (most recent call last):
  File "/usr/local/bin/thug", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/thug/thug.py", line 334, in main
    Thug(sys.argv[1:])()
  File "/usr/local/lib/python2.7/dist-packages/thug/ThugAPI/ThugAPI.py", line 86, in __call__
    self.analyze()
  File "/usr/local/lib/python2.7/dist-packages/thug/thug.py", line 324, in analyze
    ThugPlugins(PRE_ANALYSIS_PLUGINS, self)()
  File "/usr/local/lib/python2.7/dist-packages/thug/Plugins/ThugPlugins.py", line 44, in __init__
    self.get_plugins()
  File "/usr/local/lib/python2.7/dist-packages/thug/Plugins/ThugPlugins.py", line 68, in get_plugins
    for p in os.listdir(PLUGINS_PATH):
OSError: [Errno 2] No such file or directory: '/etc/thug/plugins'

```

I have followed the installation guide step by step and it is now at the Usage section? Am I meant to install the Docker too or is there something else I have missed?

Thank you for your help in advance!

**Comment by buffer** [comment]
Have you executed 'pip install thug' as root in order to install Thug? It seems like the /etc/thug directory was not properly created. In case you already did it, please try running (as root) "pip uninstall thug; pip install thug". Let me know if this fixes.

**Comment by Waffles-2** [comment]
Yup I tried doing `sudo pip install thug` it seems to install all the directories correctly except `/etc/thug/plugins`.

**Comment by buffer** [comment]
So the directory `etc/thug` was correctly created?

**Comment by Waffles-2** [comment]
yep that directory is created with the following files:

- honeyagent.conf.sample
- logging.conf.default
- virustotal.conf.default

Folders in /etc/thug:

- Personalities
- rules
- scripts

**Comment by buffer** [comment]
It seems like you're missing another directory `hooks`. Can you try removing the `/etc/thug` and installing Thug again?

**Comment by Waffles-2** [comment]
My mistake there is no directory `/etc/thug` being created at all, although there is `/usr/local/lib/python2.7/dist-packages/etc/thug/` with the above listed folders & files in.

**Comment by Waffles-2** [comment]
Tried changing the plugins directory to `Plugins` in the thug folder `/usr/local/lib/python2.7/dist-packages/thug/Plugins` and now getting a different error `Key Error: winxpie60` which I guess is because there are no available user agents? 

How do I go about setting up user agents?

**Comment by Waffles-2** [comment]
Solved:
Uninstall thug and clone the git repository instead then do the setup build & setup install. Now all is working.

**Comment by buffer** [comment]
I really suspect that Ubuntu is messing up some details. Can you try these steps?

sudo su -
pip uninstall thug
pip install thug

PS Cloning the repo is not the real solution even if it fixed your installation.

**Comment by Waffles-2** [comment]
Ok thanks for the heads up. I followed your steps but it didn't work so I had to add some more here:

sudo su -
pip uninstall thug
pip install thug **(failed)**
exit
(I was getting errors with pysocks and python-magic so uninstall them and reinstalled the latest versions)
pip uninstall pysocks
pip install pysocks
pip uninstall python-magic
pip install python-magic
pip install thug


Now it is all working, thank you for your help @buffer

**Comment by buffer** [comment]
Glad you did it!
