### ISSUE TITLE
UnicodeDecodeError in MongoDB.py

### ISSUE THREAD

**Issue by jgru** [buffer/thug#311]
Dear maintainers, 

I stumbled upon an UnicodeDecodeError in MongoDB.py by using ThugAPI.py (roughly as described in https://buffer.github.io/thug/doc/api.html)

The error stems from the following bytestring: `b'/**\r\n* Copyright\xa9 2005-2006...' `, which contains the byte `\xa9` as you can see. This produces the below mentioned stacktrace and can be fixed by modifying line 443 of MongoDB.py from 
https://github.com/buffer/thug/blob/f0df857ef5d26b682328f4ba0077efa79f78ee9e/thug/Logging/modules/MongoDB.py#L433

to 

```
enc_data = data if isinstance(data, six.string_types) else data.decode(errors='replace')
```

Here is the stacktrace in question including the URL which produced the error. 

```
Traceback (most recent call last):
  File "project/thug_service.py", line 90, in <module>
    js = t.analyze("https://webconf.vc.dfn.de/df-20201117-m117/")
  File "project/thug_service.py", line 76, in analyze
    self.run_remote(url)
  File "project/venv/lib/python3.8/site-packages/thug/ThugAPI/ThugAPI.py", line 517, in run_remote
    self.__run(window)
  File "project/venv/lib/python3.8/site-packages/thug/ThugAPI/ThugAPI.py", line 445, in __run
    dft.run()
  File "project/venv/lib/python3.8/site-packages/thug/DOM/DFT.py", line 1486, in run
    self._run()
  File "project/venv/lib/python3.8/site-packages/thug/DOM/DFT.py", line 1428, in _run
    if not self.do_handle(child, soup):
  File "project/venv/lib/python3.8/site-packages/thug/DOM/DFT.py", line 1340, in do_handle
    handler(child)
  File "project/venv/lib/python3.8/site-packages/thug/DOM/DFT.py", line 621, in handle_script
    handler(script)
  File "project/venv/lib/python3.8/site-packages/thug/DOM/DFT.py", line 743, in handle_javascript
    self.handle_external_javascript(script)
  File project/venv/lib/python3.8/site-packages/thug/DOM/DFT.py", line 689, in handle_external_javascript
    log.ThugLogging.add_code_snippet(response.content, 'Javascript', 'External')
  File "project/venv/lib/python3.8/site-packages/thug/Logging/ThugLogging.py", line 163, in add_code_snippet
    m(snippet, language, relationship, tag.hex, method)
  File "project/venv/lib/python3.8/site-packages/thug/Logging/modules/MongoDB.py", line 445, in add_code_snippet
    'snippet'      : self.fix(snippet, drop_spaces = False),
  File "project/venv/lib/python3.8/site-packages/thug/Logging/modules/MongoDB.py", line 434, in fix
    enc_data = data if isinstance(data, six.string_types) else data.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 16: invalid start byte
```

Best regards, 
jgru

P.S.: Thank you for providing such a great tool!

**Comment by buffer** [comment]
Thanks for opening the issue. Really appreciate. I pushed a patch a few seconds ago. Can you please give it a try and confirm it fixes the issue? Thanks.

**Comment by jgru** [comment]
Thanks for your fast reaction! I just tested the fix and it works completely fine! Thanks!

(FYI I just sent you an email concerning Thug's development. I would be glad if you have a look at it.)
