### ISSUE TITLE
No module named '_STPyV8'

### ISSUE THREAD

**Issue by romyolaz** [buffer/thug#360]
I'm installing thug in an Ubuntu VM on an M1 Mac. I thought I was able to satisfy all the dependencies, but get this error when trying to run thug. 

Traceback (most recent call last):
  File "/home/parallels/.local/bin/thug", line 5, in <module>
    from thug.thug import main
  File "/home/parallels/.local/lib/python3.10/site-packages/thug/thug.py", line 24, in <module>
    from .ThugAPI import ThugAPI
  File "/home/parallels/.local/lib/python3.10/site-packages/thug/ThugAPI/__init__.py", line 1, in <module>
    from .ThugAPI import ThugAPI
  File "/home/parallels/.local/lib/python3.10/site-packages/thug/ThugAPI/ThugAPI.py", line 32, in <module>
    from thug.DOM.Window import Window
  File "/home/parallels/.local/lib/python3.10/site-packages/thug/DOM/Window.py", line 39, in <module>
    from thug.DOM.W3C import File
  File "/home/parallels/.local/lib/python3.10/site-packages/thug/DOM/W3C/File/__init__.py", line 4, in <module>
    from .Blob import Blob
  File "/home/parallels/.local/lib/python3.10/site-packages/thug/DOM/W3C/File/Blob.py", line 23, in <module>
    import STPyV8
  File "/home/parallels/.local/lib/python3.10/site-packages/STPyV8.py", line 10, in <module>
    import _STPyV8
ModuleNotFoundError: No module named '_STPyV8'

What's the difference between STPyV8 and _STPyV8? How do I fix this?

Ubuntu version 22.04.2 (x86_64 emulation)
Python 3.10.12
MacBook Pro M1 Max

**Comment by buffer** [comment]
You failed installing STPyV8. Be aware that no binary wheels currently exist for M1 so you are required to build STPyV8 manually. Hopefully this will change in the next future (I am the STPyV8 maintainer too)
